apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-modernized-wcfservice
  labels:
    app: eshop-wfcservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-wfcservice
  template:
    metadata:
      name: eshop-wcfservice
      labels:
        app: eshop-wfcservice
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: eshop-wcf
        image: acr54uvnxvfxeua6.azurecr.io/eshop/wcfservice:latest
        resources:
          requests:
            cpu: "0.5"
            memory: "500M"
          limits:
            cpu: "1"
            memory: 800M
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: eshop-wcfservice-svc
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: eshop-wcfservice