apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-mvc-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: eshop-staging.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: eshop-mvc-svc
            port:
              number: 80
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: eshop-mvc-svc
            port:
              number: 80