apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-modernized-webforms
  labels:
    app: eshop-webforms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-webforms
  minReadySeconds: 5
  template:
    metadata:
      name: eshop-webforms
      labels:
        app: eshop-webforms
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: eshop-mvc
        image: acr54uvnxvfxeua6.azurecr.io/eshop/webforms:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "500M"
          limits:
            cpu: "1"
            memory: 800M
        ports:
          - containerPort: 80
        env:
        - name: UseMockData
          value: "True"
        - name: UseCustomizationData
          value: "False"
        - name: ConnectionString
          value: "Server=sql-data;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word"
        - name: UseAzureStorage
          value: "False"
        - name: StorageConnectionString
          value: ""
        - name: AppInsightsInstrumentationKey
          value: ""
        - name: UseAzureActiveDirectory
          value: "False"
        - name: AzureActiveDirectoryClientId
          value: ""
        - name: AzureActiveDirectoryTenant
          value: ""
        - name: PostLogoutRedirectUri
          value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: eshop-webforms-svc
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: eshop-webforms